// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IpAddress struct {
	ID          pgtype.UUID        `json:"id"`
	Address     string             `json:"address"`
	IsAllocated bool               `json:"is_allocated"`
	ServerID    pgtype.UUID        `json:"server_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Server struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Region           string             `json:"region"`
	Status           string             `json:"status"`
	Address          string             `json:"address"`
	Type             string             `json:"type"`
	ProvisionedAt    pgtype.Timestamptz `json:"provisioned_at"`
	LastStatusUpdate pgtype.Timestamptz `json:"last_status_update"`
	UptimeSeconds    int64              `json:"uptime_seconds"`
	HourlyCost       float64            `json:"hourly_cost"`
	LifecycleLogs    []byte             `json:"lifecycle_logs"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
